//
// module_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void part1_ispc(const float * Q, const float * K, float * QK_t, float * V, float * O, const int32_t b, const int32_t h, const int32_t H, const int32_t N, const int32_t d);
    extern void part2_ispc(const float * Q, const float * K, float * QK_t, float * V, float * O, const int32_t b, const int32_t h, const int32_t H, const int32_t N, const int32_t d, const int32_t L);
    extern void part3_ispc(const float * Q, const float * K, const float * V, float * O, float * ORow, const int32_t b, const int32_t h, const int32_t H, const int32_t N, const int32_t d, const int32_t i);
    extern void part4_ispc(const float * Q, const float * K, const float * V, float * O, float * Sij, float * Pij, float * Kj, float * Vj, float * Qi, float * Oi, float * l, float * li, float * lij, float * lnew, const int32_t b, const int32_t h, const int32_t H, const int32_t N, const int32_t d, const int32_t i, const int32_t j, const int32_t Br, const int32_t Bc);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
